version: '3'
services:
  ros:
    image: ros2-osx-full
    command: tail -f /dev/null
    volumes: 
      - ../src:/home/ros2_ws/src
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
  
  novnc:
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=yes
    ports:
      - "8080:8080"
    networks:
      - x11

networks:
  x11: